name=SnappyXOShield
version=0.1.0
author=Samar Singh <singhsamar10101@gmail.com>
maintainer=Samar Singh <singhsamar10101@gmail.com>
sentence=Motor control library for the SnappyXO Shield.
paragraph=Provides simplified motor control for use with the SnappyXO Motor Shield.
category=Device Control
url=https://github.com/samar-01/SnappyXOShield
architectures=avr
