name=SnappyXOShield
version=0.1.3
author=Samar Singh
maintainer=Samar Singh
sentence=Motor control library for the SnappyXO Shield.
paragraph=Provides simplified motor control for use with the SnappyXO Motor Shield.
category=Device Control
url=https://github.com/snappyxo/SnappyXOShield
includes=SnappyXOShield.h
architectures=*
